# ============================================
#  MySQL Deployment
# ============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "elitemart_db"
            - name: MYSQL_USER
              value: "elitemart"
            - name: MYSQL_PASSWORD
              value: "elitemart123"
---
# ============================================
#  EliteMart Spring Boot App Deployment
# ============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elitemart-app
  labels:
    app: elitemart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elitemart
  template:
    metadata:
      labels:
        app: elitemart
    spec:
      containers:
        - name: elitemart
          image: vnit2075/elitemart-docker-jenkins-app  # ← change to your Docker Hub username
          ports:
            - containerPort: 8085
          env:
            - name: SERVER_PORT
              value: "8085"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/elitemart_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "elitemart"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "elitemart123"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
